services:
  app:
    build: .
    container_name: go_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db
    networks:
      - appnet
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "appuser", "-d", "appdb" ]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  appnet:
